### PR TITLE
RFC: Feature request: responsive design #14

### PR DESCRIPTION
**Pull request by jspsoft**
### Description of PR.

As Banners module was only able to render table-based design, we set ourselves the challenge of making it responsive. We think the template approach is the most flexible one and, for now, we've only modified Banners module with this aim in mind.
Vendors module has not been modified at all: although there's a lot of improvement to be made when managing vendors, campaigns and banners, this wasn't our first purpose.

Banners module settings has now a mode option: if you leave it as Legacy, module will work as before, and your banners will be rendered into a table, vertically or horizontally.
But if you choose the option Template you'll see four new fields that will allow you to set the usual header-repeater-footer template for this Banners module.
Enter the "Header template", "Image banner template", "Footer template" and "Text banner template" fields, depending on which type of banner (image or text) you're using.
You can use four self-explanatory tokens: [LINKBANNER], [URLIMAGE], [BANNERNAME], [ALTERNATE] in these templates.
Templates can be written with standard HTML, referring to CSS classes accross your web site.

Francisco Perez Andres
Jesus Sainz-Pardo

## Changes made
banneroptions.ascx to write the templates.
displaybanners.ascx 
other minor changes with corrections

## PR Template Checklist

- [ ] Fixes Bug
- [x] Feature solution
- [ ] Other

## Please mark which issue is solved
RFC: Feature request: responsive design #14

### CODE REVIEW

**Comment by valadas** [comment]
Thanks for your contribution @jspsoft , I did not yet have time to do a full review and testing, but one concern is the references where changed from Nuget to local ones, this will not work in CI environments, can you correct that part please.

**Comment by jspsoft** [comment]
> Thanks for your contribution @jspsoft , I did not yet have time to do a full review and testing, but one concern is the references where changed from Nuget to local ones, this will not work in CI environments, can you correct that part please.

@valadas I think you mean these DLL's that are in the _external_ path:
image
They were like that in the original. I have not changed them.
I have searched and I have not found the reference in nuget.org.
For example for Telerik.Web.UI.dll

**Comment by valadas** [comment]
No, I was talking about the ones that got changed:
image

Those where using Nuget packages previously and got changed to direct references. If you want you could also improve it to use the deprecated ones from Nuget too, the package is called DotNetNuke.Web.Deprecated and then update those references to the packages folder instead of the externals folders.

Let me know if you are confortable making that change, if not, I will just add a separate issue to fix that after this merge. Let me know.

**Comment by jspsoft** [comment]
@valadas I do not have much experience with Github. I must have made some mistake but I do not know when.
In the local version I see it right.
image

I will try to erase everything and start over.
Thanks for your help

**Comment by valadas** [comment]
Oh, if you do not have much experience with github, I can fix that after the fact. You can leave the PR as is and I can submit another one after to fix CI builds and update some stuff to the community standards, that is fine.

**Comment by jspsoft** [comment]
@valadas Thank you. I will be more careful next time.

**Pull request merged**
